/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 House.glb --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube012: THREE.Mesh
    Cube021: THREE.Mesh
    Cube026: THREE.Mesh
    Cube033: THREE.Mesh
    Door001: THREE.Mesh
    Door002: THREE.Mesh
    Door003: THREE.Mesh
    Door004: THREE.Mesh
    Door005_1: THREE.Mesh
    Door005_2: THREE.Mesh
    Door006_1: THREE.Mesh
    Door006_2: THREE.Mesh
    Door007: THREE.Mesh
    Door008: THREE.Mesh
    Door009: THREE.Mesh
    Door010: THREE.Mesh
    Door011: THREE.Mesh
    Door012: THREE.Mesh
    Door013: THREE.Mesh
    Door014: THREE.Mesh
    Door015: THREE.Mesh
    Door016: THREE.Mesh
    DoorFrame: THREE.Mesh
    DoorFrame001: THREE.Mesh
    DoorFrame002: THREE.Mesh
    DoorFrame003: THREE.Mesh
    DoorFrame004: THREE.Mesh
    DoorFrame005: THREE.Mesh
    DoorFrame006: THREE.Mesh
    DoorFrame007: THREE.Mesh
    DoorFrame008: THREE.Mesh
    DoorFrame009: THREE.Mesh
    DoorFrame010: THREE.Mesh
    DoorFrame011: THREE.Mesh
    DoorFrame012: THREE.Mesh
    DoorFrame013: THREE.Mesh
    DoorFrame014: THREE.Mesh
    DoorFrame015: THREE.Mesh
    Handle_Back001: THREE.Mesh
    Handle_Back002: THREE.Mesh
    Handle_Back003: THREE.Mesh
    Handle_Back004: THREE.Mesh
    Handle_Back005: THREE.Mesh
    Handle_Back006: THREE.Mesh
    Handle_Back007: THREE.Mesh
    Handle_Back008: THREE.Mesh
    Handle_Back009: THREE.Mesh
    Handle_Back010: THREE.Mesh
    Handle_Back011: THREE.Mesh
    Handle_Back012: THREE.Mesh
    Handle_Back013: THREE.Mesh
    Handle_Back014: THREE.Mesh
    Handle_Back015: THREE.Mesh
    Handle_Back016: THREE.Mesh
    Handle_Front001: THREE.Mesh
    Handle_Front002: THREE.Mesh
    Handle_Front003: THREE.Mesh
    Handle_Front004: THREE.Mesh
    Handle_Front005: THREE.Mesh
    Handle_Front006: THREE.Mesh
    Handle_Front007: THREE.Mesh
    Handle_Front008: THREE.Mesh
    Handle_Front009: THREE.Mesh
    Handle_Front010: THREE.Mesh
    Handle_Front011: THREE.Mesh
    Handle_Front012: THREE.Mesh
    Handle_Front013: THREE.Mesh
    Handle_Front014: THREE.Mesh
    Handle_Front015: THREE.Mesh
    Handle_Front016: THREE.Mesh
    Plane: THREE.Mesh
    Plane001: THREE.Mesh
    Plane002: THREE.Mesh
    Plane003: THREE.Mesh
    Plane004: THREE.Mesh
    Plane005: THREE.Mesh
    Plane006: THREE.Mesh
    Plane007: THREE.Mesh
    Plane008: THREE.Mesh
    Plane009: THREE.Mesh
    Plane010: THREE.Mesh
    Plane011: THREE.Mesh
    Plane012: THREE.Mesh
    Plane013: THREE.Mesh
    Plane014: THREE.Mesh
    Plane018_1: THREE.Mesh
    Plane018_2: THREE.Mesh
    Plane018_3: THREE.Mesh
    Plane019_1: THREE.Mesh
    Plane019_2: THREE.Mesh
    Plane019_3: THREE.Mesh
    Plane022: THREE.Mesh
    Plane022_1: THREE.Mesh
    Plane017_1: THREE.Mesh
    Plane017_2: THREE.Mesh
    Plane019: THREE.Mesh
    Plane005_1: THREE.Mesh
    Plane005_2: THREE.Mesh
    Plane005_3: THREE.Mesh
    Plane005_4: THREE.Mesh
    Stairs006: THREE.Mesh
    Stairs006_1: THREE.Mesh
    strop: THREE.Mesh
    Cube039: THREE.Mesh
    Cube039_1: THREE.Mesh
    Cube039_2: THREE.Mesh
    Cube039_3: THREE.Mesh
    Cube038: THREE.Mesh
    Cube038_1: THREE.Mesh
    Cube038_2: THREE.Mesh
    Cube038_3: THREE.Mesh
    walls003: THREE.Mesh
    Window001_1: THREE.Mesh
    Window001_2: THREE.Mesh
    Window001_3: THREE.Mesh
    Window002_1: THREE.Mesh
    Window002_2: THREE.Mesh
    Window002_3: THREE.Mesh
    Window002_4: THREE.Mesh
    Window003_1: THREE.Mesh
    Window003_2: THREE.Mesh
    Window003_3: THREE.Mesh
    Window004: THREE.Mesh
    Window004_1: THREE.Mesh
    Window004_2: THREE.Mesh
    Window004_3: THREE.Mesh
    Window008_1: THREE.Mesh
    Window008_2: THREE.Mesh
    Window008_3: THREE.Mesh
    Window008_4: THREE.Mesh
    Window009_1: THREE.Mesh
    Window009_2: THREE.Mesh
    Window009_3: THREE.Mesh
    Window009_4: THREE.Mesh
    Window010_1: THREE.Mesh
    Window010_2: THREE.Mesh
    Window010_3: THREE.Mesh
    Window010_4: THREE.Mesh
    Window012_1: THREE.Mesh
    Window012_2: THREE.Mesh
    Window012_3: THREE.Mesh
    Window012_4: THREE.Mesh
    Window013_1: THREE.Mesh
    Window013_2: THREE.Mesh
    Window013_3: THREE.Mesh
    Window000: THREE.Mesh
    Window000_1: THREE.Mesh
    Window000_2: THREE.Mesh
    Window006_1: THREE.Mesh
    Window006_2: THREE.Mesh
    Window006_3: THREE.Mesh
    Window006_4: THREE.Mesh
    Window011_1: THREE.Mesh
    Window011_2: THREE.Mesh
    Window011_3: THREE.Mesh
    Window011_4: THREE.Mesh
    Window014_1: THREE.Mesh
    Window014_2: THREE.Mesh
    Window014_3: THREE.Mesh
    Window015_1: THREE.Mesh
    Window015_2: THREE.Mesh
    Window015_3: THREE.Mesh
    Window015_4: THREE.Mesh
    Window016_1: THREE.Mesh
    Window016_2: THREE.Mesh
    Window016_3: THREE.Mesh
    Window016_4: THREE.Mesh
    Window017_1: THREE.Mesh
    Window017_2: THREE.Mesh
    Window017_3: THREE.Mesh
    Window017_4: THREE.Mesh
    Window018_1: THREE.Mesh
    Window018_2: THREE.Mesh
    Window018_3: THREE.Mesh
    Window018_4: THREE.Mesh
    Window019_1: THREE.Mesh
    Window019_2: THREE.Mesh
    Window019_3: THREE.Mesh
    Window019_4: THREE.Mesh
    Window020_1: THREE.Mesh
    Window020_2: THREE.Mesh
    Window020_3: THREE.Mesh
    Window021_1: THREE.Mesh
    Window021_2: THREE.Mesh
    Window021_3: THREE.Mesh
    Window022_1: THREE.Mesh
    Window022_2: THREE.Mesh
    Window022_3: THREE.Mesh
    Window026_1: THREE.Mesh
    Window026_2: THREE.Mesh
    Window026_3: THREE.Mesh
    Window026_4: THREE.Mesh
    Window036: THREE.Mesh
    Window036_1: THREE.Mesh
    Window036_2: THREE.Mesh
  }
  materials: {
    ['stucco indoor']: THREE.MeshStandardMaterial
    Concrete_obruby: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    Handle_material: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
    Parquetlight_1K: THREE.MeshStandardMaterial
    MarbleFloorTiles_1K: THREE.MeshStandardMaterial
    glazed: THREE.MeshStandardMaterial
    PlainRedBricks_1K: THREE.MeshStandardMaterial
    omitka: THREE.MeshStandardMaterial
    ['tasky.001']: THREE.MeshStandardMaterial
    okap: THREE.MeshStandardMaterial
    ['black.001']: THREE.MeshStandardMaterial
    ['stucco yellow outdoor.001']: THREE.MeshStandardMaterial
    ['stucco dark']: THREE.MeshStandardMaterial
    pozink: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function HouseModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/apartments/03/House.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['stucco indoor']} position={[3.781, 2.699, 2.023]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Concrete_obruby} position={[1.906, 0.414, 5.684]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.Concrete_obruby} position={[0.406, 0.414, 5.684]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials.Wood} position={[1.965, 1.319, 4.904]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials.Wood} position={[3.836, 4.749, 3.688]} />
      <mesh geometry={nodes.Cube026.geometry} material={materials.Wood} position={[5.345, 4.749, -4.974]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials.Handle_material} position={[4.363, 1.352, -3.369]} />
      <mesh geometry={nodes.Door001.geometry} material={materials.Wood} position={[-0.956, 2.249, -1.628]} />
      <mesh geometry={nodes.Door002.geometry} material={materials.Wood} position={[-0.622, 2.249, -1.628]} />
      <mesh geometry={nodes.Door003.geometry} material={materials.Wood} position={[-2.092, 2.249, -2.954]} />
      <mesh geometry={nodes.Door004.geometry} material={materials.Wood} position={[-2.589, 2.249, -1.52]} />
      <group position={[3.851, 2.249, -1.854]}>
        <mesh geometry={nodes.Door005_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Door005_2.geometry} material={materials.Glass} />
      </group>
      <group position={[3.851, 5.254, -1.854]}>
        <mesh geometry={nodes.Door006_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Door006_2.geometry} material={materials.Glass} />
      </group>
      <mesh geometry={nodes.Door007.geometry} material={materials.Wood} position={[0.457, 5.254, 3.67]} />
      <mesh geometry={nodes.Door008.geometry} material={materials.Wood} position={[-0.956, 5.254, -1.628]} />
      <mesh geometry={nodes.Door009.geometry} material={materials.Wood} position={[-0.622, 5.254, -1.628]} />
      <mesh geometry={nodes.Door010.geometry} material={materials.Wood} position={[-1.336, 5.254, 0.661]} />
      <mesh geometry={nodes.Door011.geometry} material={materials.Wood} position={[-2.092, 5.249, -2.954]} />
      <mesh geometry={nodes.Door012.geometry} material={materials.Wood} position={[2.225, 5.254, -1.76]} />
      <mesh geometry={nodes.Door013.geometry} material={materials.Wood} position={[1.891, 5.254, -1.76]} />
      <mesh geometry={nodes.Door014.geometry} material={materials.Wood} position={[0.268, 5.254, 2.14]} />
      <mesh geometry={nodes.Door015.geometry} material={materials.Wood} position={[0.268, 5.254, 1.806]} />
      <mesh geometry={nodes.Door016.geometry} material={materials.Wood} position={[0.508, 2.249, 3.385]} />
      <mesh geometry={nodes.DoorFrame.geometry} material={materials.Wood} position={[0.981, 1.199, 3.463]} />
      <mesh geometry={nodes.DoorFrame001.geometry} material={materials.Wood} position={[-1.354, 1.199, -1.608]} />
      <mesh geometry={nodes.DoorFrame002.geometry} material={materials.Wood} position={[-0.224, 1.199, -1.608]} />
      <mesh geometry={nodes.DoorFrame003.geometry} material={materials.Wood} position={[-2.104, 1.199, -3.277]} />
      <mesh geometry={nodes.DoorFrame004.geometry} material={materials.Wood} position={[-2.576, 1.199, -1.197]} />
      <mesh geometry={nodes.DoorFrame005.geometry} material={materials.Wood} position={[3.87, 1.199, -2.252]} />
      <mesh geometry={nodes.DoorFrame006.geometry} material={materials.Wood} position={[3.87, 4.204, -2.252]} />
      <mesh geometry={nodes.DoorFrame007.geometry} material={materials.Wood} position={[0.438, 4.204, 4.068]} />
      <mesh geometry={nodes.DoorFrame008.geometry} material={materials.Wood} position={[-1.354, 4.204, -1.608]} />
      <mesh geometry={nodes.DoorFrame009.geometry} material={materials.Wood} position={[-0.224, 4.204, -1.608]} />
      <mesh geometry={nodes.DoorFrame010.geometry} material={materials.Wood} position={[-0.938, 4.204, 0.641]} />
      <mesh geometry={nodes.DoorFrame011.geometry} material={materials.Wood} position={[-2.104, 4.199, -3.277]} />
      <mesh geometry={nodes.DoorFrame012.geometry} material={materials.Wood} position={[2.548, 4.204, -1.772]} />
      <mesh geometry={nodes.DoorFrame013.geometry} material={materials.Wood} position={[1.568, 4.204, -1.772]} />
      <mesh geometry={nodes.DoorFrame014.geometry} material={materials.Wood} position={[0.256, 4.204, 2.463]} />
      <mesh geometry={nodes.DoorFrame015.geometry} material={materials.Wood} position={[0.256, 4.204, 1.483]} />
      <mesh
        geometry={nodes.Handle_Back001.geometry}
        material={materials.Handle_material}
        position={[-1.482, 2.249, -2.144]}
      />
      <mesh
        geometry={nodes.Handle_Back002.geometry}
        material={materials.Handle_material}
        position={[-0.097, 2.249, -2.144]}
      />
      <mesh
        geometry={nodes.Handle_Back003.geometry}
        material={materials.Handle_material}
        position={[-1.689, 2.249, -3.363]}
      />
      <mesh
        geometry={nodes.Handle_Back004.geometry}
        material={materials.Handle_material}
        position={[-2.991, 2.249, -1.111]}
      />
      <mesh
        geometry={nodes.Handle_Back005.geometry}
        material={materials.Handle_material}
        position={[3.857, 2.249, -2.59]}
      />
      <mesh
        geometry={nodes.Handle_Back006.geometry}
        material={materials.Handle_material}
        position={[3.857, 5.254, -2.59]}
      />
      <mesh
        geometry={nodes.Handle_Back007.geometry}
        material={materials.Handle_material}
        position={[0.445, 5.254, 4.406]}
      />
      <mesh
        geometry={nodes.Handle_Back008.geometry}
        material={materials.Handle_material}
        position={[-1.482, 5.254, -2.144]}
      />
      <mesh
        geometry={nodes.Handle_Back009.geometry}
        material={materials.Handle_material}
        position={[-0.097, 5.254, -2.144]}
      />
      <mesh
        geometry={nodes.Handle_Back010.geometry}
        material={materials.Handle_material}
        position={[-0.811, 5.254, 1.177]}
      />
      <mesh
        geometry={nodes.Handle_Back011.geometry}
        material={materials.Handle_material}
        position={[-1.689, 5.249, -3.363]}
      />
      <mesh
        geometry={nodes.Handle_Back012.geometry}
        material={materials.Handle_material}
        position={[2.635, 5.254, -1.357]}
      />
      <mesh
        geometry={nodes.Handle_Back013.geometry}
        material={materials.Handle_material}
        position={[1.482, 5.254, -1.357]}
      />
      <mesh
        geometry={nodes.Handle_Back014.geometry}
        material={materials.Handle_material}
        position={[0.67, 5.254, 2.549]}
      />
      <mesh
        geometry={nodes.Handle_Back015.geometry}
        material={materials.Handle_material}
        position={[0.84, 5.254, 1.754]}
      />
      <mesh
        geometry={nodes.Handle_Back016.geometry}
        material={materials.Handle_material}
        position={[1.394, 2.249, 3.392]}
      />
      <mesh
        geometry={nodes.Handle_Front001.geometry}
        material={materials.Handle_material}
        position={[-1.486, 2.249, -2.139]}
      />
      <mesh
        geometry={nodes.Handle_Front002.geometry}
        material={materials.Handle_material}
        position={[-0.093, 2.249, -2.139]}
      />
      <mesh
        geometry={nodes.Handle_Front003.geometry}
        material={materials.Handle_material}
        position={[-1.696, 2.249, -3.37]}
      />
      <mesh
        geometry={nodes.Handle_Front004.geometry}
        material={materials.Handle_material}
        position={[-2.985, 2.249, -1.104]}
      />
      <mesh
        geometry={nodes.Handle_Front005.geometry}
        material={materials.Handle_material}
        position={[3.864, 2.249, -2.59]}
      />
      <mesh
        geometry={nodes.Handle_Front006.geometry}
        material={materials.Handle_material}
        position={[3.864, 5.254, -2.59]}
      />
      <mesh
        geometry={nodes.Handle_Front007.geometry}
        material={materials.Handle_material}
        position={[0.439, 5.254, 4.406]}
      />
      <mesh
        geometry={nodes.Handle_Front008.geometry}
        material={materials.Handle_material}
        position={[-1.486, 5.254, -2.139]}
      />
      <mesh
        geometry={nodes.Handle_Front009.geometry}
        material={materials.Handle_material}
        position={[-0.093, 5.254, -2.139]}
      />
      <mesh
        geometry={nodes.Handle_Front010.geometry}
        material={materials.Handle_material}
        position={[-0.806, 5.254, 1.172]}
      />
      <mesh
        geometry={nodes.Handle_Front011.geometry}
        material={materials.Handle_material}
        position={[-1.696, 5.249, -3.37]}
      />
      <mesh
        geometry={nodes.Handle_Front012.geometry}
        material={materials.Handle_material}
        position={[2.641, 5.254, -1.364]}
      />
      <mesh
        geometry={nodes.Handle_Front013.geometry}
        material={materials.Handle_material}
        position={[1.475, 5.254, -1.364]}
      />
      <mesh
        geometry={nodes.Handle_Front014.geometry}
        material={materials.Handle_material}
        position={[0.664, 5.254, 2.556]}
      />
      <mesh
        geometry={nodes.Handle_Front015.geometry}
        material={materials.Handle_material}
        position={[0.839, 5.254, 1.745]}
      />
      <mesh
        geometry={nodes.Handle_Front016.geometry}
        material={materials.Handle_material}
        position={[1.394, 2.249, 3.488]}
      />
      <mesh geometry={nodes.Plane.geometry} material={materials.Parquetlight_1K} position={[-3.874, 1.199, 1.658]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Concrete_obruby} position={[0.326, 1.199, -3.802]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.Parquetlight_1K} position={[-3.038, 1.199, -3.25]} />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials.MarbleFloorTiles_1K}
        position={[-1.412, 1.199, -3.969]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={materials.MarbleFloorTiles_1K}
        position={[-4.107, 1.199, -0.967]}
      />
      <mesh geometry={nodes.Plane005.geometry} material={materials.Wood} position={[-4.661, 2.964, 0.428]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials.glazed} position={[-2.037, 4.204, 2.62]} />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials.MarbleFloorTiles_1K}
        position={[1.928, 4.204, 2.694]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={materials.MarbleFloorTiles_1K}
        position={[1.928, 4.204, 1.265]}
      />
      <mesh
        geometry={nodes.Plane009.geometry}
        material={materials.MarbleFloorTiles_1K}
        position={[1.928, 4.204, -0.965]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={materials.MarbleFloorTiles_1K}
        position={[3.66, 4.204, -0.965]}
      />
      <mesh geometry={nodes.Plane011.geometry} material={materials.Parquetlight_1K} position={[3.66, 4.204, -4.195]} />
      <mesh geometry={nodes.Plane012.geometry} material={materials.Parquetlight_1K} position={[-2.124, 4.204, 0.729]} />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={materials.Parquetlight_1K}
        position={[-2.608, 4.204, -2.197]}
      />
      <mesh
        geometry={nodes.Plane014.geometry}
        material={materials.MarbleFloorTiles_1K}
        position={[-0.577, 4.204, -3.096]}
      />
      <group position={[4.237, 1.199, 4.618]}>
        <mesh geometry={nodes.Plane018_1.geometry} material={materials.PlainRedBricks_1K} />
        <mesh geometry={nodes.Plane018_2.geometry} material={materials.Concrete_obruby} />
        <mesh geometry={nodes.Plane018_3.geometry} material={materials.Wood} />
      </group>
      <group position={[4.155, 1.199, -1.962]}>
        <mesh geometry={nodes.Plane019_1.geometry} material={materials.PlainRedBricks_1K} />
        <mesh geometry={nodes.Plane019_2.geometry} material={materials.Concrete_obruby} />
        <mesh geometry={nodes.Plane019_3.geometry} material={materials.Wood} />
      </group>
      <group position={[-2.714, 2.964, -0.572]}>
        <mesh geometry={nodes.Plane022.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Plane022_1.geometry} material={materials['stucco indoor']} />
      </group>
      <group position={[3.826, 3.806, 3.618]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane017_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Plane017_2.geometry} material={materials.omitka} />
      </group>
      <mesh geometry={nodes.Plane019.geometry} material={materials['tasky.001']} position={[-5.852, 7.328, -5.811]} />
      <group position={[-0.077, 10.623, -0.031]}>
        <mesh geometry={nodes.Plane005_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials.okap} />
        <mesh geometry={nodes.Plane005_3.geometry} material={materials.Parquetlight_1K} />
        <mesh geometry={nodes.Plane005_4.geometry} material={materials['black.001']} />
      </group>
      <group position={[1.156, -0.001, 6.654]}>
        <mesh geometry={nodes.Stairs006.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Stairs006_1.geometry} material={materials.Concrete_obruby} />
      </group>
      <mesh geometry={nodes.strop.geometry} material={nodes.strop.material} position={[-3.874, 7.199, 0.959]} />
      <group position={[3.781, 5.699, 2.023]}>
        <mesh geometry={nodes.Cube039.geometry} material={materials['stucco yellow outdoor.001']} />
        <mesh geometry={nodes.Cube039_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cube039_2.geometry} material={materials.Concrete_obruby} />
        <mesh geometry={nodes.Cube039_3.geometry} material={materials['stucco indoor']} />
      </group>
      <group position={[3.781, 2.699, 2.023]}>
        <mesh geometry={nodes.Cube038.geometry} material={materials['stucco yellow outdoor.001']} />
        <mesh geometry={nodes.Cube038_1.geometry} material={materials.PlainRedBricks_1K} />
        <mesh geometry={nodes.Cube038_2.geometry} material={materials['stucco indoor']} />
        <mesh geometry={nodes.Cube038_3.geometry} material={materials['stucco dark']} />
      </group>
      <mesh geometry={nodes.walls003.geometry} material={materials.Wood} position={[3.781, 5.699, 2.023]} />
      <group position={[-2.325, 1.679, 5.388]}>
        <mesh geometry={nodes.Window001_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window001_2.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window001_3.geometry} material={materials.pozink} />
      </group>
      <group position={[-3.684, 1.679, 5.131]}>
        <mesh geometry={nodes.Window002_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window002_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window002_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window002_4.geometry} material={materials.pozink} />
      </group>
      <group position={[-0.952, 1.679, 5.131]}>
        <mesh geometry={nodes.Window003_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window003_2.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window003_3.geometry} material={materials.pozink} />
      </group>
      <group position={[-5.03, 2.129, -3.382]}>
        <mesh geometry={nodes.Window004.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window004_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window004_2.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window004_3.geometry} material={materials.pozink} />
      </group>
      <group position={[-2.584, 2.129, -4.957]}>
        <mesh geometry={nodes.Window008_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window008_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window008_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window008_4.geometry} material={materials.pozink} />
      </group>
      <group position={[-1.404, 2.429, -4.959]}>
        <mesh geometry={nodes.Window009_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window009_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window009_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window009_4.geometry} material={materials.pozink} />
      </group>
      <group position={[1.468, 2.429, -4.982]}>
        <mesh geometry={nodes.Window010_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window010_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window010_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window010_4.geometry} material={materials.pozink} />
      </group>
      <group position={[3.833, 2.129, -0.322]}>
        <mesh geometry={nodes.Window012_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window012_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window012_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window012_4.geometry} material={materials.pozink} />
      </group>
      <group position={[2.426, 2.129, 3.557]}>
        <mesh geometry={nodes.Window013_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window013_2.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window013_3.geometry} material={materials.pozink} />
      </group>
      <group position={[-0.952, 4.679, 5.131]}>
        <mesh geometry={nodes.Window000.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window000_1.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window000_2.geometry} material={materials.pozink} />
      </group>
      <group position={[-3.684, 4.679, 5.131]}>
        <mesh geometry={nodes.Window006_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window006_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window006_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window006_4.geometry} material={materials.pozink} />
      </group>
      <group position={[1.474, 4.679, -4.982]}>
        <mesh geometry={nodes.Window011_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window011_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window011_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window011_4.geometry} material={materials.pozink} />
      </group>
      <group position={[-4.996, 5.129, -0.572]}>
        <mesh geometry={nodes.Window014_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window014_2.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window014_3.geometry} material={materials.pozink} />
      </group>
      <group position={[-5.03, 5.129, 2.688]}>
        <mesh geometry={nodes.Window015_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window015_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window015_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window015_4.geometry} material={materials.pozink} />
      </group>
      <group position={[-5.03, 5.129, -3.382]}>
        <mesh geometry={nodes.Window016_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window016_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window016_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window016_4.geometry} material={materials.pozink} />
      </group>
      <group position={[-1.404, 5.429, -4.959]}>
        <mesh geometry={nodes.Window017_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window017_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window017_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window017_4.geometry} material={materials.pozink} />
      </group>
      <group position={[-2.584, 5.129, -4.957]}>
        <mesh geometry={nodes.Window018_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window018_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window018_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window018_4.geometry} material={materials.pozink} />
      </group>
      <group position={[-2.325, 4.679, 5.388]}>
        <mesh geometry={nodes.Window019_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window019_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window019_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window019_4.geometry} material={materials.pozink} />
      </group>
      <group position={[3.8, 5.429, 1.193]}>
        <mesh geometry={nodes.Window020_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window020_2.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window020_3.geometry} material={materials.pozink} />
      </group>
      <group position={[3.8, 5.429, -0.535]}>
        <mesh geometry={nodes.Window021_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window021_2.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window021_3.geometry} material={materials.pozink} />
      </group>
      <group position={[3.8, 5.129, 2.463]}>
        <mesh geometry={nodes.Window022_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window022_2.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window022_3.geometry} material={materials.pozink} />
      </group>
      <group position={[-5.03, 2.129, 2.688]}>
        <mesh geometry={nodes.Window026_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window026_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window026_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window026_4.geometry} material={materials.pozink} />
      </group>
      <group position={[-4.996, 2.429, -0.572]}>
        <mesh geometry={nodes.Window036.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Window036_1.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window036_2.geometry} material={materials.pozink} />
      </group>
    </group>
  )
}

useGLTF.preload('/House.glb')
